### ISSUE TITLE
[RESOLVIDO] Procuro uma arquitetura para customizações em painel compartilhado

### ISSUE THREAD

**Issue by LukasTsunami** [alefcastelo/Forum#3]
Hey pessoal, tudo bem? Tenho um painel admnistrativo pra todos os meus sites.
Eu simplesmente mudo os dados de conexão e banco de dados e funciona o painel admnistrativo pro site (todos estão no mesmo padrão).
Sempre foi assim por muito tempo, e agora tem um novo chefe aqui, e a ordem é serem possíveis customizações personalizadas pra cada cliente.
Existe algum padrão de arquitetura para gerenciar customizações num painél compartilhado?
Estava pensando em fazer algo num esquema parecido com ACL, mas para customizações... gerenciando quais customizações cada pessoa teria acesso ou não.
Mas a infraestrutura de pacotes, aonde vão ficar os códigos personalizados e como organizar essas coisas meio que não tive uma luz de como planejar.
Caso alguém puder ajudar, agradeço.

**Comment by rafaelgou** [comment]
ACL é um bom padrão.

Se fizer desta forma, o código é um só, o acesso é liberado mediante configuração (em banco de dados, ou num arquivo `.yml`, possivelmente).

Como entendi que para cada site você entrega este painel instalado, configurar via `.yml` parece uma boa alternativa. Desta forma mantém o código unificado.

**Comment by alefcastelo** [comment]
@LukasTsunami  Você pode da uma olhada no bundle https://github.com/dmishh/SettingsBundle você consegue guardar configuração de modo global e baseado no usuário pode ser que se encaixe no que você precisa!

**Comment by vinyvicente** [comment]
@LukasTsunami , está com a ferramenta certa, porém precisa estudá-la melhor pra isso.

O Symfony é modular, e por isso, consegue separar em Bundles (Até <=4), e cada bundle em si pode haver uma hierarquia a se customizar para cada situação ou regra.

A ACL que o Rafael disse aí em cima é outro ponto, mas acho que pro seu projeto não virar um "linguição cheio de ifs", você precisa entender toda a hierarquia das coisas e como separar isso para customizar.

Vai ter customização? Procure uma estratégia que não atrapalhe o que já existe hoje. Quebre em APIs, microserviços, e se comunique através deles. É bem complexo e precisa ser bem pensado.

**Comment by vinyvicente** [comment]
boa, @alefcastelo

**Comment by alefcastelo** [comment]
@LukasTsunami essa issue foi resolvida? posso fechar?
