### ISSUE TITLE
[RESOLVIDO] Trabalhando com doctrine em testes unitários

### ISSUE THREAD

**Issue by amcosta** [alefcastelo/Forum#4]
Bom dia, tenho uma dúvida como trabalhar com o doctrine nos testes automatizados, estou usando o phpunit e tenho alguns serviços onde passo o EntityManager no construct no serviço mas parece que o teste fica complicado, como vcs costumar fazer testes com serviços que consomem dados do banco?

**Comment by alefcastelo** [comment]
@alex-moreno-costa As boas práticas definem que vc não deve passar o entitymanager como dependência, na verdade nenhum manager deve ser passado como dependência, no caso dos seus testes, se você estiver passando o entitymanager vc precisa mockar ele e depois mockar o repositório isso acaba sendo um gargalo nos seus testes, se vc injeta o repositório como dependência vc só precisa mockar ele.

**Comment by vinyvicente** [comment]
Sei que já fecharam a thread, mas minha experiência já fiz mock dos objetos, inclusive EntityManager como também tínhamos um banco à parte para as fixtures. É isso!
